### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by alex938** [marcosValle/RansPy#1]
Hello Sir,

I am currently doing a encryption/decryption project and as we trying out your script.

Are you able to help me with the following error when running "python enc.py"

```
raceback (most recent call last):
  File "enc.py", line 72, in <module>
    for filename in glob.iglob(startPath, recursive=True):
TypeError: iglob() got an unexpected keyword argument 'recursive'
```

Kind regards,

Alex.

**Comment by marcosValle** [comment]
Hi Alex! What python version are you running? If I am not mistaken you should be using 3.5+ for the recursive parameter.

**Comment by alex938** [comment]
Hi Sir,

Spot on, didn't realise that! Updated! 

```
Encrypting> /root/test/document.txt
Traceback (most recent call last):
  File "enc.py", line 75, in <module>
    encrypt_file(key, filename)
  File "enc.py", line 26, in encrypt_file
    encryptor = AES.new(key ,AES.MODE_CBC, iv)
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Cipher/AES.py", line 200, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Cipher/__init__.py", line 55, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Cipher/_mode_cbc.py", line 234, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Cipher/AES.py", line 100, in _create_base_cipher
    result = start_operation(c_uint8_ptr(key),
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Util/_raw_api.py", line 151, in c_uint8_ptr
    raise TypeError("Object type %s cannot be passed to C code" % type(data))
TypeError: Object type <class 'str'> cannot be passed to C code

Sorry my python is not the best, so I am working through it slowly, but any ideas on the above?
```

**Comment by alex938** [comment]
Ah, got it up and running, just needed a bytestring prefix in front of the key 

`key = b'this is the key woohoo123'`
